# workflow para testar o pull request

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checagem se o PR pode ser feito
        run: echo "Obrigado por criar o PR ao branch main."
